name: Fortune CI & CD

on:
    push
jobs:
    fortune:
        name: Fortune Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install --global yarn && yarn
            - name: Run fortune test
              run: yarn workspace @human-protocol/fortune-exchange-oracle-server test
            - name: Install Railway CLI
              if: success()
              run: npm install -g @railway/cli
            - name: Deploy to Railway
              if: success()
              run: |
                railway environment staging
                railway service exchange-oracle
                railway up
              env:
                RAILWAY_TOKEN: ${{ secrets.FORTUNE_RAILWAY_TOKEN }}
                POSTGRES_URL: ${{ secrets.FORTUNE_EXO_POSTGRES_URL }}
                S3_ACCESS_KEY: ${{ secrets.FORTUNE_EXO_S3_ACCESS_KEY }}
                S3_SECRET_KEY: ${{ secrets.FORTUNE_EXO_S3_SECRET_KEY }}
                WEB3_PRIVATE_KEY: ${{ secrets.FORTUNE_EXO_WEB3_PRIVATE_KEY }}